version: '2'

services:
  expenseManagerFrontend-vue:
    container_name: expense-manager-frontend
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: cjmason8/expense-manager-frontend:${TAG_NAME}
    ports:
      - 8085:80
